In [3]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array[:, 1])

[2 7]


In [19]:
bool_index = array > 5
print(type(bool_index))
index = [0, 1, 3, 4]
print(array[0, index])

<class 'numpy.ndarray'>
[1 2 4 5]


In [18]:
array_1 = np.random.randint(0, 10, size=(3,3))
print(array_1)

[[9 0 1]
 [1 9 1]
 [8 2 3]]


In [20]:
print(array_1[:2, :2])

[[9 0]
 [1 9]]


In [5]:
array_2 = np.random.randint(0, 100, size=(4,4))
print(array_2)

[[38 97 37 63]
 [78  0 97 72]
 [79 73 24  0]
 [54 37 21  6]]


In [6]:
autovalores, autovectores = np.linalg.eig(array_2)
print(autovalores)
print(autovectores)

[201.51488791 +0.j         -68.06752494+16.63567252j
 -68.06752494-16.63567252j   2.62016197 +0.j        ]
[[-0.57379647+0.j          0.62081224+0.26205831j  0.62081224-0.26205831j
   0.39354024+0.j        ]
 [-0.572514  +0.j         -0.6826085 +0.j         -0.6826085 -0.j
  -0.2157194 +0.j        ]
 [-0.49079513+0.j          0.0476159 -0.21625958j  0.0476159 +0.21625958j
  -0.71759958+0.j        ]
 [-0.31953948+0.j         -0.09136979-0.15026418j -0.09136979+0.15026418j
   0.53258057+0.j        ]]
