In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [4]:
A = np.array([[2,3],[5,7],[11,13]])
U, D, V = np.linalg.svd(A)
print(f"U: \n{U}")
print(f"D: \n{D}")
print(f"V: \n{V}")

U: 
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D: 
[19.40321383  0.71783924]
V: 
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [5]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(f"D_pse: \n{D_pse}")

D_pse: 
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print('valores a reemplazar en D_pse')
print(D_pse[:D.shape[0], :D.shape[0]])

valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [7]:
print('valores que pondremos en D_pse')
print(np.linalg.inv(np.diag(D)))

valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [8]:
print('D_pse')
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [9]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(f"A_pse: \n{A_pse}")

A_pse: 
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [10]:
A_pse = np.linalg.pinv(A)
print(f"A_pse: \n{A_pse}")

A_pse: 
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
