# **Matrices diagonales y simétricas**

In [1]:
import numpy as np

In [2]:
vector = np.array([1, 2, 3, 4, 5])
matriz = np.diag(vector)
print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
print(matriz[0:4, 0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3, 0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [7]:
A = np.diag([2,3,4,5])
v1 = np.array([[1,1,1,1]])
print(A.dot(v1.T))

[[2]
 [3]
 [4]
 [5]]


In [8]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [10]:
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
print(np.linalg.inv(A))

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]
