# **Tipos especiales de matrices**

**Identidad**

In [1]:
import numpy as np

In [3]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([[2], [3], [5], [7]])
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


**Inversa**

In [5]:
A = np.array([[1, 0, 1], [0, 1, 1], [-1, 1, 1]])

In [9]:
inversa_A = np.linalg.inv(A)
print(A)
print(inversa_A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]
[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [10]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
